### ISSUE TITLE
Support require('module/file')

### ISSUE THREAD

**Issue by mvila** [mirek/node-unused-deps#1]
Sometimes, we don't require modules directly, we only need a file inside. For example:

``` js
var file = require('module/file');
```

I think your tool (which is very useful!) should handle this case.

**Comment by azder** [comment]
Also, the same thing with:

```
    "load-grunt-config":       "^0.8.0-beta.1",
    "load-grunt-tasks":        "^0.6.0",
```

I'm using both for loading Grunt related packages, and yet, the report is:

```
    npm uninstall --save-dev grunt
    npm uninstall --save-dev grunt-bump
    npm uninstall --save-dev grunt-concurrent
    npm uninstall --save-dev grunt-contrib-clean
    npm uninstall --save-dev grunt-contrib-concat
    npm uninstall --save-dev grunt-contrib-jshint
    npm uninstall --save-dev grunt-contrib-requirejs
    npm uninstall --save-dev grunt-contrib-watch
    npm uninstall --save-dev grunt-nodemon
    npm uninstall --save-dev grunt-replace
```

**Comment by mirek** [comment]
@mvila sure, will fix soon, it should be automatic.

@azder it's doable, will have a think about it. maybe a flag to skip grunt tasks which will automatically switch to on when 'load-grunt-tasks' is used or something. catch-all auto-loaders like `load-grunt-tasks` are more tricky because they'll load automatically everything, even if it's not used. it would be great to still list unused grunt task npms.

**Comment by mirek** [comment]
@mvila it's fixed.

@azder moving your report into separate issue.

**Comment by mvila** [comment]
Fantastic! Thanks @mirek!
